In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
from scipy.stats import norm
from datetime import datetime

In [ ]:
def call_prices(r_list, sigma_list, T_list, N, s0_list, K_list):
    #df = pd.DataFrame(columns=['r','sigma','T','s0','k','t','asset','call'])
    lista = []
    counter = 0
    
    for r in r_list:
        for sigma in sigma_list:
            for T in T_list:
                for s0 in s0_list:
                    for K in K_list:
                        # Generate asset prices
                        asset = [s0*np.exp(sigma*np.sqrt(T*i/N)*np.random.normal(0, 1, size=1)[0] \
                       +(r-sigma**2/2)*T*i/N) for i in range(N)]
                            
                        # Compute call price
                        call = []
                        for i in range(len(asset)):
                            d1= (np.log(asset[i]/K)+(r+(0.5)*(sigma**2))*(T-i*(T/N))) / (sigma*np.sqrt(T-i*(T/N)))
                            d2= (np.log(asset[i]/K)+(r+(-1)*(0.5)*(sigma**2))*(T-i*(T/N))) / \
                            (sigma*np.sqrt(T-i*(T/N)))
                            c = asset[i]*(norm(0,1).cdf(d1))-K*np.exp(-1*r*(T-i*(T/N)))*(norm(0, 1).cdf(d2))
                            #df.loc[counter] = [r,sigma,T,s0,K,i,asset[i],c]
                            lista.append(np.array((r,sigma,T,s0,K,i,asset[i],c)))
                            counter+=1
                            if (counter % 10000)==0:
                                print(counter)
    return lista

In [2]:
r_list_1m = np.arange(0.05,1.05,0.1)
sigma_list_1m = np.arange(0.05,1.05,0.1)
T_list_1m = np.arange(0.1,1.1,0.1)
s0_list_1m = np.arange(10,20,1)
K_list_1m = np.arange(10,20,1)
N_1m=10
par = len(r_list_1m)*len(sigma_list_1m)*len(T_list_1m)*len(s0_list_1m)*len(K_list_1m)*N_1m
par

1000000

In [ ]:
start = datetime.now()
data = call_prices(r_list=r_list_1m, sigma_list=sigma_list_1m,\
                   T_list=T_list_1m, N=N_1m, s0_list=s0_list_1m, K_list=K_list_1m)
end = datetime.now()
total_time = (end-start).total_seconds()

10000
20000
30000
40000
50000
60000
70000
80000
90000
100000
110000
120000
130000
140000
150000
160000
170000
180000
190000
200000
210000
220000
230000
240000
250000
260000
270000
280000
290000
300000
310000
320000
330000
340000
350000
360000
370000
380000
390000
400000
410000
420000
430000
440000
450000
460000
470000
480000
490000
500000
510000
520000
530000
540000
550000
560000
570000
580000
590000
600000
610000
620000
630000
640000
650000
660000
670000
680000
690000
700000
710000
720000
730000
740000
750000
760000
770000
780000
790000
800000
810000
820000
830000
840000
850000
860000
870000
880000
890000
900000
910000
920000
930000
940000
950000
960000
970000
980000
990000
1000000

In [ ]:
df = pd.DataFrame(data, columns=['r','sigma','T','s0','k','t','asset','call'])
df

           r  sigma    T    s0     k    t      asset       call
0       0.05   0.05  0.1  10.0  10.0  0.0  10.000000   0.090978
1       0.05   0.05  0.1  10.0  10.0  1.0   9.977024   0.071240
2       0.05   0.05  0.1  10.0  10.0  2.0   9.979236   0.066344
3       0.05   0.05  0.1  10.0  10.0  3.0  10.085137   0.133263
4       0.05   0.05  0.1  10.0  10.0  4.0   9.964273   0.045868
...      ...    ...  ...   ...   ...  ...        ...        ...
999995  0.95   0.95  1.0  19.0  19.0  5.0   8.997918   1.540661
999996  0.95   0.95  1.0  19.0  19.0  6.0  51.991112  39.051605
999997  0.95   0.95  1.0  19.0  19.0  7.0  18.731183   6.045688
999998  0.95   0.95  1.0  19.0  19.0  8.0  16.556520   3.156622
999999  0.95   0.95  1.0  19.0  19.0  9.0  26.959538   9.878276

[1000000 rows x 8 columns]

In [ ]:
df['asset_greater_call'] = [True if df['asset'][i] >= df['call'][i] else False for i in range(df.shape[0])]
df

,r,sigma,T,s0,k,t,asset,call,asset_greater_call
0,0.05,0.05,0.1,10.0,10.0,0.0,10.000000,0.090978,True
1,0.05,0.05,0.1,10.0,10.0,1.0,9.977024,0.071240,True
2,0.05,0.05,0.1,10.0,10.0,2.0,9.979236,0.066344,True
3,0.05,0.05,0.1,10.0,10.0,3.0,10.085137,0.133263,True
4,0.05,0.05,0.1,10.0,10.0,4.0,9.964273,0.045868,True
...,...,...,...,...,...,...,...,...,...
999995,0.95,0.95,1.0,19.0,19.0,5.0,8.997918,1.540661,True
999996,0.95,0.95,1.0,19.0,19.0,6.0,51.991112,39.051605,True
999997,0.95,0.95,1.0,19.0,19.0,7.0,18.731183,6.045688,True
999998,0.95,0.95,1.0,19.0,19.0,8.0,16.556520,3.156622,True
999999,0.95,0.95,1.0,19.0,19.0,9.0,26.959538,9.878276,True

In [ ]:
df['asset_greater_call'].value_counts()

True    1000000
Name: asset_greater_call, dtype: int64

In [ ]:
df['scaled_call'] = [df['call'][i]/df['k'][i] for i in range(df.shape[0])]
df['scaled_asset'] = [df['s0'][i]/df['k'][i] for i in range(df.shape[0])]

In [ ]:
df

,r,sigma,T,s0,k,t,asset,call,asset_greater_call,scaled_call,scaled_asset
0,0.05,0.05,0.1,10.0,10.0,0.0,10.000000,0.090978,True,0.009098,1.0
1,0.05,0.05,0.1,10.0,10.0,1.0,9.977024,0.071240,True,0.007124,1.0
2,0.05,0.05,0.1,10.0,10.0,2.0,9.979236,0.066344,True,0.006634,1.0
3,0.05,0.05,0.1,10.0,10.0,3.0,10.085137,0.133263,True,0.013326,1.0
4,0.05,0.05,0.1,10.0,10.0,4.0,9.964273,0.045868,True,0.004587,1.0
...,...,...,...,...,...,...,...,...,...,...,...
999995,0.95,0.95,1.0,19.0,19.0,5.0,8.997918,1.540661,True,0.081087,1.0
999996,0.95,0.95,1.0,19.0,19.0,6.0,51.991112,39.051605,True,2.055348,1.0
999997,0.95,0.95,1.0,19.0,19.0,7.0,18.731183,6.045688,True,0.318194,1.0
999998,0.95,0.95,1.0,19.0,19.0,8.0,16.556520,3.156622,True,0.166138,1.0
999999,0.95,0.95,1.0,19.0,19.0,9.0,26.959538,9.878276,True,0.519909,1.0

In [ ]:
df.to_csv('data/data_lists.csv')